create table "public"."attendances" (
    "id" bigint generated by default as identity not null,
    "slot" text not null,
    "player_id" uuid not null,
    "attended" boolean not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone
);


alter table "public"."attendances" enable row level security;

alter table "public"."payments" add column "slot" text;

CREATE UNIQUE INDEX attendances_pkey ON public.attendances USING btree (id);

CREATE UNIQUE INDEX attendances_slot_player_id_idx ON public.attendances USING btree (slot, player_id);

alter table "public"."attendances" add constraint "attendances_pkey" PRIMARY KEY using index "attendances_pkey";

alter table "public"."attendances" add constraint "attendances_player_id_fkey" FOREIGN KEY (player_id) REFERENCES players(id) not valid;

alter table "public"."attendances" validate constraint "attendances_player_id_fkey";

grant delete on table "public"."attendances" to "anon";

grant insert on table "public"."attendances" to "anon";

grant references on table "public"."attendances" to "anon";

grant select on table "public"."attendances" to "anon";

grant trigger on table "public"."attendances" to "anon";

grant truncate on table "public"."attendances" to "anon";

grant update on table "public"."attendances" to "anon";

grant delete on table "public"."attendances" to "authenticated";

grant insert on table "public"."attendances" to "authenticated";

grant references on table "public"."attendances" to "authenticated";

grant select on table "public"."attendances" to "authenticated";

grant trigger on table "public"."attendances" to "authenticated";

grant truncate on table "public"."attendances" to "authenticated";

grant update on table "public"."attendances" to "authenticated";

grant delete on table "public"."attendances" to "service_role";

grant insert on table "public"."attendances" to "service_role";

grant references on table "public"."attendances" to "service_role";

grant select on table "public"."attendances" to "service_role";

grant trigger on table "public"."attendances" to "service_role";

grant truncate on table "public"."attendances" to "service_role";

grant update on table "public"."attendances" to "service_role";



