CREATE SCHEMA IF NOT EXISTS "extensions";

CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE TABLE IF NOT EXISTS "public"."attendances" (
    "id" bigint NOT NULL,
    "session" "text" NOT NULL,
    "player_id" "uuid" NOT NULL,
    "attended" boolean NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."attendances" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."attendances_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" "uuid" NOT NULL,
    "player_id" "uuid" NOT NULL,
    "amount" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "concept" "text" NOT NULL,
    "month" "text" NOT NULL,
    "is_cash" boolean DEFAULT true NOT NULL,
    "registered_by" "text" NOT NULL,
    "slot" "text" NOT NULL,
    "session" "text"
);



CREATE TABLE IF NOT EXISTS "public"."players" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "dni" "text",
    "fecha_nac" "date",
    "category" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);



ALTER TABLE ONLY "public"."attendances" ADD CONSTRAINT "attendances_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_dni_key" UNIQUE ("dni");
ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_name_not_empty" CHECK (("name" <> ''));
ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_last_name_not_empty" CHECK (("last_name" <> ''));
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_amount_positive" CHECK (("amount" > (0)::numeric));
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_concept_not_empty" CHECK (("concept" <> ''));
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_month_not_empty" CHECK (("month" <> ''));
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_concept_valid" CHECK (("concept" = ANY (ARRAY['monthly'::text, 'session'::text])));
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_concept_session_rules" CHECK ((("concept" = 'monthly'::text) AND ("session" IS NULL)) OR (("concept" = 'session'::text) AND ("session" IS NOT NULL)));
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_registered_by_not_empty" CHECK (("registered_by" <> ''));

CREATE UNIQUE INDEX "attendances_session_player_id_idx" ON "public"."attendances" USING "btree" ("session", "player_id");

CREATE INDEX "attendances_player_id_idx" ON "public"."attendances" USING "btree" ("player_id");
CREATE INDEX "payments_player_id_idx" ON "public"."payments" USING "btree" ("player_id");
CREATE INDEX "payments_month_idx" ON "public"."payments" USING "btree" ("month");

CREATE OR REPLACE TRIGGER "update_attendances_updated_at" BEFORE UPDATE ON "public"."attendances" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');
CREATE OR REPLACE TRIGGER "update_payments_updated_at" BEFORE UPDATE ON "public"."payments" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');
CREATE OR REPLACE TRIGGER "update_players_updated_at" BEFORE UPDATE ON "public"."players" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('updated_at');

ALTER TABLE ONLY "public"."attendances" ADD CONSTRAINT "attendances_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE RESTRICT;

ALTER TABLE "public"."attendances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "public"."attendances" FROM "anon";
REVOKE ALL ON TABLE "public"."payments" FROM "anon";
REVOKE ALL ON TABLE "public"."players" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."attendances_id_seq" FROM "anon";

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."attendances" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."payments" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."players" TO "authenticated";

GRANT USAGE, SELECT ON SEQUENCE "public"."attendances_id_seq" TO "authenticated";

GRANT ALL ON TABLE "public"."attendances" TO "service_role";
GRANT ALL ON TABLE "public"."payments" TO "service_role";
GRANT ALL ON TABLE "public"."players" TO "service_role";

GRANT ALL ON SEQUENCE "public"."attendances_id_seq" TO "service_role";
