CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "public";

CREATE TABLE IF NOT EXISTS "public"."attendances" (
    "id" bigint NOT NULL,
    "slot" "text" NOT NULL,
    "player_id" "uuid" NOT NULL,
    "attended" boolean NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone
);

ALTER TABLE "public"."attendances" OWNER TO "postgres";

ALTER TABLE "public"."attendances" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."attendances_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" bigint NOT NULL,
    "player_id" "uuid" NOT NULL,
    "amount" numeric NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "concept" "text" NOT NULL,
    "is_cash" boolean DEFAULT true NOT NULL,
    "registered_by" "text" NOT NULL,
    "slot" "text"
);

ALTER TABLE "public"."payments" OWNER TO "postgres";

ALTER TABLE "public"."payments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."payments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."players" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "alias" "text" NOT NULL,
    "name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "dni" "text",
    "category" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "nick" "text"
);

ALTER TABLE "public"."players" OWNER TO "postgres";



ALTER TABLE ONLY "public"."attendances" ADD CONSTRAINT "attendances_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_alias_key" UNIQUE ("alias");
ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_dni_key" UNIQUE ("dni");
ALTER TABLE ONLY "public"."players" ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "attendances_slot_player_id_idx" ON "public"."attendances" USING "btree" ("slot", "player_id");

CREATE OR REPLACE TRIGGER "update_payments_updated_at" BEFORE UPDATE ON "public"."payments" FOR EACH ROW EXECUTE FUNCTION "public"."moddatetime"('updated_at');
CREATE OR REPLACE TRIGGER "update_players_updated_at" BEFORE UPDATE ON "public"."players" FOR EACH ROW EXECUTE FUNCTION "public"."moddatetime"('updated_at');

ALTER TABLE ONLY "public"."attendances" ADD CONSTRAINT "attendances_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");
ALTER TABLE ONLY "public"."payments" ADD CONSTRAINT "payments_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");

ALTER TABLE "public"."attendances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."attendances" TO "anon";
GRANT ALL ON TABLE "public"."attendances" TO "authenticated";
GRANT ALL ON TABLE "public"."attendances" TO "service_role";

GRANT ALL ON SEQUENCE "public"."attendances_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."attendances_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."attendances_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."payments" TO "anon";
GRANT ALL ON TABLE "public"."payments" TO "authenticated";
GRANT ALL ON TABLE "public"."payments" TO "service_role";

GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."players" TO "anon";
GRANT ALL ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";
